library(mia)
library(SummarizedExperiment)

# ── Read seq-table TSV ────────────────────────────────────────────────────────
# Rows: ASVs; columns: sequence_id, then one per sample
# Generated by: dada2-rs seq-table-to-tsv
seq_tsv <- read.table("seqtab.tsv", sep = "\t", header = TRUE,
                      row.names = 1, check.names = FALSE)

# ── Read taxonomy TSV ─────────────────────────────────────────────────────────
# Rows: ASVs; columns: sequence_id, then one per rank (Kingdom … Species)
# Generated by: dada2-rs tax-to-tsv
tax_tsv <- read.table("taxonomy.tsv", sep = "\t", header = TRUE,
                      row.names = 1, check.names = FALSE)

# ── Align to shared ASVs ──────────────────────────────────────────────────────
shared <- intersect(rownames(seq_tsv), rownames(tax_tsv))
if (length(shared) == 0) stop("No shared sequence IDs between the two tables.")

count_mat <- as.matrix(seq_tsv[shared, , drop = FALSE])  # ASVs x samples
tax_df    <- tax_tsv[shared, , drop = FALSE]              # ASVs x ranks

# ── Build TreeSummarizedExperiment ────────────────────────────────────────────
# Optional: load sample metadata and pass as colData = DataFrame(sample_meta[colnames(count_mat), ])
tse <- TreeSummarizedExperiment(
    assays  = list(counts = count_mat),
    rowData = DataFrame(tax_df)
)

tse
